language: cpp
sudo: required
os: linux
dist: trusty


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
    packages:
      - qt510base
      - qt510script
      - qt510declarative
      - qt510tools
      - qt510x11extras
      - qt510svg
      - qt510quickcontrols2
      - ninja-build
      - libxcb-keysyms1-dev
      - libxml2-utils
      - libudev-dev
      - texinfo
#      - modemmanager
#      - modemmanager-dev
#      - libwayland-dev
#      - libegl1-mesa-dev
      - pkg-config
      - g++-7
      - gcc-7
      - libqrencode-dev
      - libdmtx-dev
      - libattr1-dev
      - libphonon4qt5-dev
      - libphonon4qt5experimental-dev
      - liburi-perl
      - docbook-xml
      - docbook-xsl
      - libboost-all-dev
      - liblmdb-dev
      - gperf
      - wget

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

install:
  # Update CMake
  - wget https://cmake.org/files/v3.11/cmake-3.11.0-rc3-Linux-x86_64.tar.gz -O- | sudo tar xz -C /usr --strip-components=1

script:
  - source /opt/qt510/bin/qt510-env.sh
#  - ./build_frameworks.sh -i ~/kf5-debug -t Debug -g Ninja -o ~/kf5-gcc-linux64-debug.tar.xz
  - ./build_frameworks.sh -i ~/kf5-release -t Release -g Ninja -o ~/kf5-gcc7-linux64-release.tar.xz -a "-DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7"

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh ~/kf5-gcc7-linux64-debug.tar.xz ~/kf5-gcc7-linux64-release.tar.xz
