language: cpp
sudo: true
os: linux
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
    packages:
      - qt510base
      - qt510script
      - qt510declarative
      - qt510tools
      - qt510x11extras
      - qt510svg
      - qt510quickcontrols2
      - ninja-build
      - libxcb-keysyms1-dev
      - libxml2-utils
      - libudev-dev
      - texinfo
#      - modemmanager
#      - modemmanager-dev
#      - libwayland-dev
#      - libegl1-mesa-dev
      - pkg-config
      - g++-7
      - gcc-7
      - libqrencode-dev
      - libdmtx-dev
      - libattr1-dev
      - libphonon4qt5-dev
      - libphonon4qt5experimental-dev
      - liburi-perl
      - docbook-xml
      - docbook-xsl
      - libboost-all-dev
      - liblmdb-dev
      - gperf
      - wget

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

env:
  global:
    - KF5_BUILD_TYPE="Release"
    - BUILD_GENERATOR="Ninja"
    - KF5_INSTALL_DIR="${HOME}/kf5-build-output"
    - KF5_VERSION=5.45.0
    - EXTRA_CMAKE_ARGS="-DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7"
    - PACKAGE_FILE_NAME="kf5-${KF5_VERSION}-${KF5_BUILD_TYPE}-ubuntu-trusty-amd64.tar.xz"

cache:
  directories:
  - ${KF5_INSTALL_DIR}


before_install:
  # Update CMake
  - mkdir $HOME/cmake
  - wget https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.tar.gz -O- | tar xz -C $HOME/cmake --strip-components=1
  - export PATH="$PATH:$HOME/cmake/bin"
  - source /opt/qt510/bin/qt510-env.sh

jobs:
  include:
    - stage: TIER_1
      script:
      - mkdir -p ${KF5_INSTALL_DIR}
      - rm -rf ${KF5_INSTALL_DIR}/*
      - ./build_frameworks.sh -i ${KF5_INSTALL_DIR} -t ${KF5_BUILD_TYPE} -g ${BUILD_GENERATOR} -a "${EXTRA_CMAKE_ARGS}"
      - find $CACHE_DIR
    - stage: TIER_2
      script:
      - find $CACHE_DIR
      - ./build_frameworks.sh -i ${KF5_INSTALL_DIR} -t ${KF5_BUILD_TYPE} -g ${BUILD_GENERATOR} -a "${EXTRA_CMAKE_ARGS}"
    - stage: TIER_3.1
      script:
      - ./build_frameworks.sh -i ${KF5_INSTALL_DIR} -t ${KF5_BUILD_TYPE} -g ${BUILD_GENERATOR} -a "${EXTRA_CMAKE_ARGS}"
    - stage: TIER_3.2
      script:
      - ./build_frameworks.sh -i ${KF5_INSTALL_DIR} -t ${KF5_BUILD_TYPE} -g ${BUILD_GENERATOR} -a "${EXTRA_CMAKE_ARGS}"
    - stage: upload
      script:
      - rm ${KF5_INSTALL_DIR}/*BUILT*
      - ./pack.sh ${KF5_INSTALL_DIR} $HOME/${PACKAGE_FILE_NAME}
      - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      - bash ./upload.sh $HOME/${PACKAGE_FILE_NAME}
      - rm -rf ${KF5_INSTALL_DIR}/*
